applicationName: CWDS TEMPLATE API
version: ${APP_VERSION:-local}

server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 9081
  requestLog:
    appenders:
      - type: console

shiro:
  iniConfigs: ["file:${SHIRO_CONFIG_PATH:-config/shiro_nosec.ini}"]

swagger:
  templateName: swagger.mustache
  assetsPath: /static
  resourcePackage: gov.ca.cwds.templateate.web.rest
  title: CWDS TEMPLATE API
  description: RESTful TEMPLATE API.
  logo: images/CWDS-API-Logo-Horizontal.png
  loginUrl: ${LOGIN_URL:-http://localhost:8080/authn/login/}
  logoutUrl: ${LOGOUT_URL:-http://localhost:8080/perry/authn/logout}
  showSwagger: ${SHOW_SWAGGER:-true}
  jsonUrl: ${SWAGGER_JSON_URL:-http://localhost:8080/swagger.json}
  callbackUrl: ${SWAGGER_CALLBACK_URL:-http://localhost:8080/swagger}

upgardeDbOnStart: ${UPGRADE_DB_ON_START:-true}

templateDataSourceFactory:
  driverClass: org.postgresql.Driver
  user: ${DB_TEMPLATE_USER:-postgres}
  password: ${DB_TEMPLATE_PASSWORD:-postgres}
  url: ${DB_TEMPLATE_JDBC_URL:-jdbc:postgresql://localhost:5432/postgres}
  validationQuery: "select count(*) from ${DB_TEMPLATE_DEFAULT_SCHEMA:-template}.template_instance"
  logValidationErrors: true
  initialSize: ${DB_TEMPLATE_CP_INITIAL_SIZE:-2}
  minSize: ${DB_TEMPLATE_CP_MIN_SIZE:-2}
  maxSize: ${DB_TEMPLATE_CP_MAX_SIZE:-8}
  minIdleTime: 1 minute
  properties:
      hibernate.dialect: gov.ca.cwds.templateate.persistence.hibernate.dialect.JsonbSupportPostgreSQL9Dialect
      hibernate.id.new_generator_mappings: false
      hibernate.show_sql: true
      hibernate.default_schema: ${DB_TEMPLATE_DEFAULT_SCHEMA:-template}
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.cache.use_query_cache: false
      hibernate.connection.autocommit: false

webSecurity:
  httpResponseSecurityHeaders:
    # Prevent MIMI sniffing
    X-Content-Type-Options: nosniff

    # Prevent click-jacking
    X-Frame-Options: deny

    # Prevent cross site scripting
    X-XSS-Protection: 1; mode=block

    # Prevent everything other than same origin
    Content-Security-Policy: default-src 'self' 'unsafe-inline';

logging:
  level: ${LOGLEVEL:-DEBUG}
  loggers:
    "org.hibernate.SQL":
      level: DEBUG
    "org.hibernate.type.descriptor.sql":
      level: DEBUG
    "AUDIT":
      level: ALL
    "gov.ca.cwds":
      level: DEBUG
  appenders:
    - type: console
      threshold: DEBUG
      timeZone: UTC
      target: stdout
      logFormat: '[%X{remoteAddress}] [%date{ISO8601}] [%level] [%thread] [%X{uniqueId}] [%logger:] [%message]%n'